#!/usr/bin/env bash

set -euo pipefail

: "${YES:=0}"

if [ "$YES" != "1" ]; then
  exit 1
fi

: "${GANDI_API_KEY:=XXX}"
: "${DOMAIN_NAME:=example.com}"

update_gandi_nameservers() {
  local name_servers="$1" # comma separated string
  local domain_name="$2"
  local api_key="$3"

  local api_uri="https://api.gandi.net/v5/domain/domains/$domain_name"
  local gandi_nameservers=

  mkdir -p priv

  curl -s -X GET "$api_uri"/livedns \
      -H "authorization: Apikey $api_key" > priv/gandi_nameservers.json

  gandi_nameservers=$(jq -c -r '.nameservers' priv/gandi_nameservers.json)

  name_servers=$(echo "console.log(JSON.stringify(\"$name_servers\".split(',')))" | node)

  (echo \
    "a=$name_servers;b=$gandi_nameservers;c=a.filter(x => !b.includes(x));process.exit(c.length ? 1 : 0)" | node) \
    || (curl -X PUT "$api_uri"/nameservers \
        -H "authorization: Apikey $api_key" \
        -H 'content-type: application/json' \
        -d "{\"nameservers\":$name_servers}")
}

update_gandi_nameservers "$1" "$DOMAIN_NAME" "$GANDI_API_KEY"
