name: build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:


jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.14.0]
        python-version: [3.10]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up node modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-node${{ matrix.node-version }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-node${{ matrix.node-version }}-build-
            ${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Install modules
        run: npm install && npm install --save-dev @rollup/rollup-linux-x64-gnu

      - name: Build favicons
        run: |
          ./generate-favicons.js favicon.svg

      - name: Build pages
        run: python generate.py config.json

      - name: Build styles
        run: npm run sass

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/**/*
